#!/usr/bin/env python3
###定数###
#COMMON
OPERATING_MODE_REFUSE_ALL_USERS_EXCEPT_ALLOWED_USERS = 0
OPERATING_MODE_APPROVE_ALL_USERS_EXCEPT_BANNED_USERS = 1
STANDBY_STATUS_READY = 0
STANDBY_STATUS_ON_BATCH_PROCESS = 1
STANDBY_STATUS_WAITING_BATCH_PROCESS_RECALCULATE = 2
STANDBY_STATUS_BATCH_PROCESSED_FAILURE = 3
DAY_SUNDAY = 0
DAY_MONDAY = 1
DAY_TUESDAY = 2
DAY_WEDNESDAY = 3
DAY_THURSDAY = 4
DAY_FRIDAY = 5
DAY_SATURDAY = 6
#UserInfo
USER_UNREGISTERED = 0
USER_UNALLOWED = 1
USER_ALLOWED = 2
USER_BANNED = 3
STAGE_CHANGE_REMIND_TYPE_NOTHING = 0
STAGE_CHANGE_REMIND_TYPE_DAY_OF_WEEK = 1
STAGE_CHANGE_REMIND_TYPE_DAYS = 2
STAGE_CHANGE_REMIND_VALUE_MONDAY = 0
STAGE_CHANGE_REMIND_VALUE_TUESDAY = 1
STAGE_CHANGE_REMIND_VALUE_WEDNESDAY = 2
STAGE_CHANGE_REMIND_VALUE_THURSDAY = 3
STAGE_CHANGE_REMIND_VALUE_FRIDAY = 4
STAGE_CHANGE_REMIND_VALUE_SATURDAY = 5
STAGE_CHANGE_REMIND_VALUE_SUNDAY = 6
STATUS_READY = 0
STATUS_ON_BATCH_PROCESS = 1
STATUS_ON_WAITING_FOR_BATCH_RECALCULATION = 2
STATUS_BATCH_PROCESSED_FAILURE = 3
#WorkingRecord
PROCESS_CATEGORY_MAINTENANCE = 0
PROCESS_CATEGORY_RECORD_WORKING_HOURS = 1
PROCESS_CATEGORY_MEMO_ONLY = 3
PROCESS_STATUS_MAINTENANCE = 0
PROCESS_STATUS_NOT_STARTED = 1
PROCESS_STATUS_ON_RECORDING = 2
PROCESS_STATUS_RECORDED_SUCCESS = 3
PROCESS_STATUS_RECORDED_FAILURE = 4
PROCESS_STATUS_MEMO_ONLY = 5
#WEEKDAY
WEEKDAY = ['月曜日', '火曜日', '水曜日', '木曜日', '金曜日', '土曜日', '日曜日']
#BATCH
BATCH_TYPE_MARK_FOR_RESERVE_RECALCULATION = 0
BATCH_TYPE_EXECUTE_RECALCULATION = 1
BATCH_TYPE_FIND_DEFECTED_USER_INFO_RECORDS_AND_MARK_STATUS_FAILURE = 2
BATCH_TYPE_FIND_DEFECTED_WORKING_RECORDS_AND_MARK_STATUS_FAILURE = 3
